### ISSUE TITLE
Custom Calendar error in typescript  ::: Uncaught TypeError: Cannot read properties of undefined (reading 'index') at r.value (index.module.js:1:1) , All work in *.js

### ISSUE THREAD

**Issue by fanstar** [shahabyazdi/react-multi-date-picker#136]
Uncaught TypeError: Cannot read properties of undefined (reading 'index')
    at r.value (index.module.js:1:1)
    at index.js:1:1
    at index.js:1:1
    at mountMemo (react-dom.development.js:15846:1)
    at Object.useMemo (react-dom.development.js:16219:1)
    at Object.useMemo (react.development.js:1532:1)
    at k (index.js:1:1)
    at renderWithHooks (react-dom.development.js:14985:1)
    at mountIndeterminateComponent (react-dom.development.js:17811:1)
    at beginWork (react-dom.development.js:19049:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:1)
    at invokeGuardedCallback (react-dom.development.js:4056:1)
    at beginWork$1 (react-dom.development.js:23964:1)
    at performUnitOfWork (react-dom.development.js:22776:1)
    at workLoopSync (react-dom.development.js:22707:1)
    at renderRootSync (react-dom.development.js:22670:1)
    at performSyncWorkOnRoot (react-dom.development.js:22293:1)
    at react-dom.development.js:11327:1
    at unstable_runWithPriority (scheduler.development.js:468:1)
    at runWithPriority$1 (react-dom.development.js:11276:1)
    at flushSyncCallbackQueueImpl (react-dom.development.js:11322:1)
    at flushSyncCallbackQueue (react-dom.development.js:11309:1)
    at flushPassiveEffectsImpl (react-dom.development.js:23620:1)
    at unstable_runWithPriority (scheduler.development.js:468:1)
    at runWithPriority$1 (react-dom.development.js:11276:1)
    at flushPassiveEffects (react-dom.development.js:23447:1)
    at react-dom.development.js:23324:1
    at workLoop (scheduler.development.js:417:1)
    at flushWork (scheduler.development.js:390:1)
    at MessagePort.performWorkUntilDeadline (scheduler.development.js:157:1)

=========================================
My Custom Script:
=========================================
thai.tsx
```
import DateObject, { Calendar } from "react-date-object";

const getMonthLengths = (isLeap: boolean) => {
    return [31, isLeap ? 29 : 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31];
}

const isLeap = (year: number) => {
    return (year % 4 === 0 && year % 100 !== 0) || year % 400 === 0;
}

const getLeaps = (currentYear: number) => {
    if (currentYear === 0) return [];

    let year = currentYear > 0 ? 1 : -1;

    const leaps = [];
    const condition = () => { return currentYear > 0 ? year <= currentYear : currentYear <= year; }
    const increase = () => {
        if (currentYear > 0) {
            year += 1
        } else {
            year -= 1
        }
        return year;
    }

    while (condition()) {
        if (isLeap(year)) leaps.push(year);

        increase();
    }

    return leaps;
}

const getDayOfYear = ({ year, month, day }: DateObject) => {
    const monthLengths = getMonthLengths(isLeap(year));

    for (let i = 0; i < month.index; i+=1) {
        day += monthLengths[i];
    }

    return day;
}

const leapsLength = (year: number) => {
    return (
        (((year - 1) / 4) || 0) +
        (-((year - 1) / 100) || 0) +
        (((year - 1) / 400) || 0)
    );
}

const myYearLentgh  = 365;
const getAllDays = (date: DateObject) => {
    const { year } = date;

    return (
        myYearLentgh  * (year - 1) +
        leapsLength(year) +
        getDayOfYear(date)
    );
}

const guessYear = (days: number, currentYear: number) => {
    // const year = ~~(days / 365.24);
    const year = Math.floor(days / 365.24);

    return year + (currentYear > 0 ? 1 : -1);
}
const thai: Calendar = {
    name: "thai",
    startYear: 1,
    yearLength: myYearLentgh ,
    epoch: 1523097,
    century: 25,
    weekStartDayIndex: 1,
    getMonthLengths,
    isLeap,
    getLeaps,
    getDayOfYear,
    getAllDays,
    leapsLength,
    guessYear,
};

export default thai;
```

=========================================
// Try to test ===> get error!
=========================================
App.tsx
```
import React from 'react';
import { Calendar } from 'react-multi-date-picker';
import './App.css';
import thai from './thai';

function App() {
  return (
    <div className="App">
      <Calendar calendar={thai} />
    </div>
  );
}

export default App;
```

**Comment by fanstar** [comment]
E

**Comment by fanstar** [comment]
Fixed here:
const leapsLength = (year: number) => {
    return (
        (((year - 1) / 4) | 0) +
        (-((year - 1) / 100) | 0) +
        (((year - 1) / 400) | 0)
    );
}
